### model
model_name_or_path: Qwen/Qwen3-Coder-30B-A3B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: verifier_part0,verifier_part1,verifier_part2,verifier_part3,verifier_part4,verifier_part5,verifier_part6,verifier_part7,verifier_part8
template: qwen3_nothink
cutoff_len: 131072
rope_scaling: yarn
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/SWE-Lego-Verifier-30B-A3B
logging_steps: 1
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
weight_decay: 0.01
max_grad_norm: 1.0
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
enable_liger_kernel: true
use_unsloth_gc: true
flash_attn: fa2
