### model
model_name_or_path: Qwen/Qwen3-32B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: swe_lego_real_trajectories_sample2k,swe_lego_synthetic_trajectories_sample2k
template: qwen3_nothink
cutoff_len: 131072
rope_scaling: yarn
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
turn_mask: true # set to false if you don't want to use error_mask

### output
output_dir: saves/SWE-Lego-Qwen3-32B
logging_steps: 1
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
weight_decay: 0.01
max_grad_norm: 1.0
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
enable_liger_kernel: true
use_unsloth_gc: true
flash_attn: fa2